// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEg0aEgIPzje0ScJ9Ts8ktgJWUrrpQWWI',
    appId: '1:777048642283:web:09b6bb901db982b2ce64ae',
    messagingSenderId: '777048642283',
    projectId: 'groceryapp-a6b6d',
    authDomain: 'groceryapp-a6b6d.firebaseapp.com',
    storageBucket: 'groceryapp-a6b6d.appspot.com',
    measurementId: 'G-F8KY24L40T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY02qP3P34IGj1_CFmG-hoXdPVLyet5aE',
    appId: '1:777048642283:android:82271e0bf3868cedce64ae',
    messagingSenderId: '777048642283',
    projectId: 'groceryapp-a6b6d',
    storageBucket: 'groceryapp-a6b6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj9_TZWiJqJALzjs253lRfE2C_8M1_Vic',
    appId: '1:777048642283:ios:7bfbc4d82cbf0cebce64ae',
    messagingSenderId: '777048642283',
    projectId: 'groceryapp-a6b6d',
    storageBucket: 'groceryapp-a6b6d.appspot.com',
    iosBundleId: 'com.example.grocerymarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj9_TZWiJqJALzjs253lRfE2C_8M1_Vic',
    appId: '1:777048642283:ios:7bfbc4d82cbf0cebce64ae',
    messagingSenderId: '777048642283',
    projectId: 'groceryapp-a6b6d',
    storageBucket: 'groceryapp-a6b6d.appspot.com',
    iosBundleId: 'com.example.grocerymarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEg0aEgIPzje0ScJ9Ts8ktgJWUrrpQWWI',
    appId: '1:777048642283:web:1e32ca14f1ba43f2ce64ae',
    messagingSenderId: '777048642283',
    projectId: 'groceryapp-a6b6d',
    authDomain: 'groceryapp-a6b6d.firebaseapp.com',
    storageBucket: 'groceryapp-a6b6d.appspot.com',
    measurementId: 'G-MK00EZPPRC',
  );
}
